### ISSUE TITLE
Missing mini-icons in Stats screen

### ISSUE THREAD

**Issue by atomsymbol** [openchia/mobile#11]
Clickable boxes, but missing mini-icons: BLOCKS, FARMERS, REWARDS.

The mini-icons in the 3 boxes should be different from the already existing mini-icons used in CHIA_PRICE and POOL_SPACE.

**Comment by BubbleTrouble14** [comment]
Oh sorry forgot to check up on issues on github. Yes I will add that thx 👌🏼
