### ISSUE TITLE
Wrong block height displayed

### ISSUE THREAD

**Issue by dreamboostme** [openchia/mobile#16]
In the farmer statistics of my blocks, the height is indicated by one more than it actually is.

In the website, the height is correct.

Android, v2.2.0

**Comment by BubbleTrouble14** [comment]
Okay will have a look. Could you maybe tell me your launcherId, would make it easier to debug.

**Comment by dreamboostme** [comment]
LauncherId: 6989b6aa0d7df476a17f2aaf9d5abbceaabbb7a3324219078953df4a454b2596
Block in mobile: 2178967
Real block: 2178966

**Comment by BubbleTrouble14** [comment]
Okay I'll get it fixed and push a new update then.
