### ISSUE TITLE
Different count of most recent partials in 12h vs 24h mode

### ISSUE THREAD

**Issue by atomsymbol** [openchia/mobile#6]
App version: v1.1.2-alpha

Steps to reproduce:

1. Select a farmer
2. Go to Partials screen
3. Finger touch one of the bars on the right of the chart to display the number of partials corresponding to the touched bar

Actual results:

- 24h mode:
  - Nov 26 11:00 PM - Nov 27 01:00 AM: **10 partials**

- 12h mode:
  - Nov 26 11:00 PM - Nov 27 12:00 AM: **12 partials**
  - Nov 27 12:00 AM - Nov 27 01:00 AM: **10 partials**

Expected results:

- 24h mode:
  - Nov 26 11:00 PM - Nov 27 01:00 AM: **12+10=22 partials**

Local time: 2021-Nov-27 01:57 CET

**Comment by BubbleTrouble14** [comment]
I'll have a look thx.

**Comment by BubbleTrouble14** [comment]
Should be fixed now.
